"""empty message

Revision ID: 47063a152ce7
Revises: 
Create Date: 2021-01-13 17:55:30.118358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47063a152ce7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('bought', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_item_user_id'), 'shopping_item', ['user_id'], unique=False)
    op.create_table('user_stuff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('spending_limit', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stuff_email'), 'user_stuff', ['email'], unique=True)
    op.create_index(op.f('ix_user_stuff_username'), 'user_stuff', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stuff_username'), table_name='user_stuff')
    op.drop_index(op.f('ix_user_stuff_email'), table_name='user_stuff')
    op.drop_table('user_stuff')
    op.drop_index(op.f('ix_shopping_item_user_id'), table_name='shopping_item')
    op.drop_table('shopping_item')
    # ### end Alembic commands ###
