"""empty message

Revision ID: 9805ad7109f4
Revises: 4b94472bbb1d
Create Date: 2020-12-16 16:45:50.933041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9805ad7109f4'
down_revision = '4b94472bbb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stuff', sa.Column('api_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stuff', 'api_key')
    # ### end Alembic commands ###
