"""empty message

Revision ID: cba8b2968f9d
Revises: 9805ad7109f4
Create Date: 2021-01-04 15:05:15.366900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba8b2968f9d'
down_revision = '9805ad7109f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_item', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_item', 'price')
    # ### end Alembic commands ###
